import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'ms' | 'en';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary - Comprehensive coverage of all UI text
const translations: Record<Language, Record<string, string>> = {
    ms: {
        // Common
        'language': 'Bahasa',
'dashboard': 'Laman Utama',
'settings': 'Tetapan Sistem',
'logout': 'Keluar',
'profile': 'Profil Saya',
'notifications': 'Makluman',
'menu': 'Menu Utama',
'closeMenu': 'Tutup Menu',



        // App Header
        'header.tagline': 'Empowering Farmers Through Technology 🌾',

        // Farmer Dashboard
        'farmer.dashboard.title': 'Laman Utama Petani',

'farmer.dashboard.welcome': 'Hai {name}! Selamat kembali 👋',
'farmer.dashboard.description': 'Panduan pembelajaran padi yang ringkas, jelas dan mudah digunakan',
'farmer.dashboard.startLearning': 'Mari Belajar',
'farmer.dashboard.statistics': 'Ringkasan Aktiviti',
'farmer.dashboard.quickAccess': 'Akses Pantas Modul',
'farmer.dashboard.recentUpdates': 'Kemas Kini Terkini',
'farmer.dashboard.viewAll': 'Lihat Semua',
'farmer.dashboard.noUpdates': 'Belum ada kemas kini',
'farmer.dashboard.checkLater': 'Semak semula nanti untuk info baharu',
'farmer.dashboard.pendingReports': 'Laporan Belum Selesai',
'farmer.dashboard.pendingReportsNeedAction': 'Perlu tindakan anda',
'farmer.dashboard.unreadAnnouncements': 'Pengumuman Baharu',
'farmer.dashboard.fromAdmin': 'Daripada Pentadbir',



        // Admin Dashboard
       'admin.dashboard.title': 'Laman Utama Pentadbir',
'admin.dashboard.subtitle': 'Pantau sistem & urus tugasan dengan mudah',
'admin.dashboard.urgentAction': 'Laporan Perlu Tindakan Segera',
'admin.dashboard.urgentDescription': 'Ada laporan belum disemak. Jom semak dan beri maklum balas',
'admin.dashboard.reviewNow': 'Semak Sekarang',
'admin.dashboard.priorityActions': 'Tindakan Penting Hari Ini',
'admin.dashboard.contentManagement': 'Urus Kandungan',
'admin.dashboard.quickActions': 'Tindakan Pantas',
'admin.dashboard.reportsRequiringAction': 'Laporan Belum Selesai',
'admin.dashboard.recentRegistrations': 'Pengguna Baharu',
'admin.dashboard.pendingReports': 'Laporan Belum Disemak',
'admin.dashboard.inReview': 'Sedang Disemak',
'admin.dashboard.resolved': 'Selesai',
'admin.dashboard.totalUsers': 'Jumlah Pengguna',
'admin.dashboard.actionRequired': 'Perlu Tindakan',
'admin.dashboard.allHandled': 'Semua laporan telah selesai',
'admin.dashboard.continueReview': 'Teruskan Semakan',
'admin.dashboard.noInProcess': 'Tiada laporan dalam proses',
'admin.dashboard.resolvedThisMonth': 'Selesai Bulan Ini',
'admin.dashboard.farmersAndAdmins': 'Petani • Pentadbir',
'admin.dashboard.manageForum': 'Urus Forum',
'admin.dashboard.addContent': 'Tambah Kandungan',
'admin.dashboard.createAnnouncement': 'Buat Pengumuman',
'admin.dashboard.noPendingReports': 'Tiada Laporan Tertunda',
'admin.dashboard.allProcessed': 'Semua laporan telah diuruskan',
'admin.dashboard.noNewRegistrations': 'Tiada Pengguna Baharu',
'admin.dashboard.checkBackForNew': 'Semak semula nanti untuk pengguna baharu',
'admin.dashboard.highPriority': 'PENTING',
'admin.dashboard.mediumPriority': 'BIASA',
'admin.dashboard.reviewReports': 'Semak Laporan',
'admin.dashboard.mainAction': 'Tindakan Utama',
'admin.dashboard.notifyFarmers': 'Maklumkan Petani',
'admin.dashboard.farmersAdmins': 'Senarai Petani & Pentadbir',
'admin.dashboard.learningMaterials': 'Bahan Pembelajaran',
'admin.dashboard.menuAdmin': 'Menu Pentadbir',



      // Modules
'modules.learning': 'Bahan Pembelajaran',
'modules.learning.desc': 'Belajar tentang padi dengan cara yang mudah & jelas',
'modules.virtualTour': 'Lawatan Maya Ladang',
'modules.virtualTour.desc': 'Terokai ladang contoh melalui lawatan maya 360°',
'modules.announcements': 'Pengumuman',
'modules.announcements.desc': 'Ikuti berita terkini & maklumat penting daripada pentadbir',
'modules.reports': 'Pelaporan',
'modules.reports.desc': 'Hantar laporan masalah ladang dengan gambar & lokasi',
'modules.forum': 'Forum Komuniti',
'modules.forum.desc': 'Bincang, tanya soalan & kongsi pengalaman dengan petani lain',
'modules.feedback': 'Maklum Balas',
'modules.feedback.desc': 'Kongsikan cadangan anda untuk tambah baik sistem AgriPadi',

// Stats
'stats.materialsAvailable': 'Bahan Tersedia',
'stats.communityMembers': 'Ahli Komuniti',
'stats.forumTopics': 'Topik Forum',
'stats.videosDocuments': 'Video & Dokumen Panduan',
'stats.activeFarmers': 'Petani Aktif',
'stats.discussions': 'Perbincangan & Soalan',
'stats.pendingReports': 'Laporan Belum Selesai',
'stats.inReview': 'Sedang Disemak',
'stats.resolved': 'Selesai',
'stats.totalUsers': 'Jumlah Pengguna',

// Actions
'actions.accessNow': 'Akses Sekarang',
'actions.viewAll': 'Lihat Semua',
'actions.viewAllAlt': 'Lihat Semua',
'actions.reviewReports': 'Semak Laporan',
'actions.createAnnouncement': 'Buat Pengumuman',
'actions.manageUsers': 'Urus Pengguna',
'actions.uploadContent': 'Tambah Kandungan',



        // Time
        'time.monthsAgo': 'bulan lalu',
        'time.daysAgo': 'hari lalu',
        'time.hoursAgo': 'jam lalu',
        'time.minutesAgo': 'minit lalu',

       // Navigation
'nav.dashboard': 'Laman Utama',
'nav.userManagement': 'Urus Pengguna',
'nav.learning': 'Bahan Pembelajaran',
'nav.virtualTour': 'Lawatan Maya Sawah Padi',
'nav.announcements': 'Pengumuman',
'nav.reports': 'Laporan Ladang',
'nav.forum': 'Forum Komuniti',
'nav.feedback': 'Maklum Balas',
'nav.settings': 'Tetapan Akaun',
'nav.priorityActions': 'Tindakan Penting',
'nav.management': 'Pengurusan',
'nav.contentManagement': 'Urus Kandungan',
'nav.learningSection': 'Bahagian Pembelajaran',
'nav.communicationSection': 'Bahagian Komunikasi',

// Roles
'role.farmer': 'Petani Padi',
'role.admin': 'Pentadbir Sistem',
'role.farmerShort': 'Petani',
'role.adminShort': 'Pentadbir',

// Announcements Page
'announcements.title': 'Pengumuman',
'announcements.subtitle': 'Ikuti info terkini & pengumuman penting',
'announcements.noAnnouncements': 'Belum ada pengumuman buat masa ini',
'announcements.by': 'Ditulis oleh',

// Learning Materials Page
'learning.title': 'Bahan Pembelajaran',
'learning.subtitle': 'Akses video & dokumen pembelajaran pertanian',
'learning.totalMaterials': 'Jumlah Bahan',
'learning.youtubeVideos': 'Video YouTube',
'learning.pdfDocuments': 'Dokumen PDF',
'learning.searchPlaceholder': 'Cari bahan pembelajaran...',
'learning.category': 'Kategori',
'learning.allCategories': 'Semua',
'learning.video': 'Video',
'learning.pdf': 'PDF',
'learning.videoYoutube': 'Video YouTube',
'learning.pdfDocument': 'Dokumen PDF',
'learning.noMaterialsFound': 'Tiada bahan dijumpai',
'learning.noMaterialsAvailable': 'Tiada bahan tersedia',
'learning.pdfAvailable': 'Dokumen PDF sedia untuk dimuat turun',
'learning.openPdf': 'Buka PDF',
'learning.uploadedBy': 'Dimuat naik oleh',

// Reports Page
'reports.title': 'Laporan Ladang',
'reports.subtitle': 'Laporkan masalah atau isu di ladang anda',
'reports.submitNew': 'Hantar Laporan Baharu',
'reports.noReports': 'Belum ada laporan. Klik butang di atas untuk buat laporan baharu',
'reports.viewDetails': 'Lihat Butiran',
'reports.edit': 'Edit',
'reports.delete': 'Padam',
'reports.confirmDelete': 'Padam laporan ini? Tindakan tidak boleh dibatalkan',
'reports.status.pending': 'Belum Disemak',
'reports.status.under_review': 'Sedang Disemak',
'reports.status.resolved': 'Selesai',
'reports.adminResponse': 'Maklum Balas Pegawai Pertanian',
'reports.respondedOn': 'Dijawab pada',
'reports.submittedOn': 'Dihantar pada',
'reports.type': 'Jenis',
'reports.location': 'Lokasi',
'reports.description': 'Penerangan',
'reports.image': 'Gambar',
'reports.pdfLetter': 'Surat PDF',
'reports.viewPdfLetter': 'Lihat Surat PDF',
'reports.close': 'Tutup',



     // Report Form
'reports.form.createTitle': 'Hantar Laporan Baharu',
'reports.form.createDescription': 'Isikan maklumat berkaitan masalah di sawah padi anda',
'reports.form.editTitle': 'Edit Laporan',
'reports.form.editDescription': 'Kemaskini maklumat laporan anda',
'reports.form.reportTitle': 'Tajuk Laporan *',
'reports.form.titlePlaceholder': 'Contoh: Masalah Bekalan Air',
'reports.form.problemType': 'Jenis Masalah *',
'reports.form.selectProblemType': 'Pilih jenis masalah',
'reports.form.type.irrigation': 'Masalah Pengairan',
'reports.form.type.pestControl': 'Kawalan Perosak',
'reports.form.type.soilManagement': 'Pengurusan Tanah',
'reports.form.type.plantDisease': 'Penyakit Tanaman',
'reports.form.type.other': 'Lain-lain',
'reports.form.farmLocation': 'Lokasi Ladang *',
'reports.form.locationPlaceholder': 'Contoh: Lot 1, Kg. Labuan Kota Belud',
'reports.form.problemDescription': 'Penerangan Masalah *',
'reports.form.descriptionPlaceholder': 'Terangkan masalah yang anda hadapi...',
'reports.form.imageOptional': 'Gambar (Pilihan)',
'reports.form.clickToUploadImage': 'Klik untuk muat naik gambar',
'reports.form.imageFormat': 'PNG, JPG, GIF sehingga 10MB',
'reports.form.pdfLetterOptional': 'Surat PDF (Pilihan)',
'reports.form.clickToUploadPdf': 'Klik untuk muat naik surat PDF',
'reports.form.pdfFormat': 'PDF sehingga 10MB',
'reports.form.cancel': 'Batal',
'reports.form.submit': 'Hantar Laporan',
'reports.form.submitting': 'Sedang dihantar...',
'reports.form.update': 'Kemas Kini',

// Reports Form (Update/Edit)
'reports.form.updating': 'Sedang dikemas kini...',
'reports.form.newImage': 'Gambar Baharu (Pilihan)',
'reports.form.newPdf': 'Surat PDF Baharu (Pilihan)',
'reports.form.leaveBlankNoChange': 'Biarkan kosong jika tidak mahu ubah',
'reports.form.detailsTitle': 'Butiran Laporan',



// Forum Page
'forum.title': 'Forum Komuniti',
'forum.subtitle': 'Kongsi pengalaman & berbincang dengan petani lain',
'forum.createNew': 'Buat Forum Baharu',
'forum.noForums': 'Belum ada forum. Jom cipta forum pertama anda!',
'forum.comments': 'Komen',
'forum.justNow': 'Baru sahaja',
'forum.minutesAgo': 'minit lalu',
'forum.hoursAgo': 'jam lalu',
'forum.daysAgo': 'hari lalu',
'forum.form.createTitle': 'Buat Forum Baharu',
'forum.form.createDescription': 'Forum anda akan disemak oleh pentadbir sebelum diterbitkan',
'forum.form.title': 'Tajuk Forum *',
'forum.form.titlePlaceholder': 'Contoh: Cara mengatasi masalah perosak padi',
'forum.form.category': 'Kategori (Pilihan)',
'forum.form.selectCategory': 'Pilih kategori (pilihan)',
'forum.form.category.pestControl': 'Kawalan Perosak',
'forum.form.category.irrigation': 'Pengairan',
'forum.form.category.fertilizer': 'Baja',
'forum.form.category.harvesting': 'Penuaian',
'forum.form.category.marketing': 'Pemasaran',
'forum.form.category.other': 'Lain-lain',
'forum.form.content': 'Kandungan *',
'forum.form.contentPlaceholder': 'Kongsikan pengalaman, soalan atau maklumat anda di sini...',
'forum.form.image': 'Gambar (Pilihan)',
'forum.form.imageFormat': 'Saiz maks 5MB. Format: JPG, PNG, GIF',
'forum.form.cancel': 'Batal',
'forum.form.submit': 'Hantar untuk Semakan',
'forum.form.submitting': 'Sedang dihantar...',

// Feedback Page
'feedback.title': 'Maklum Balas',
'feedback.subtitle': 'Maklum balas anda sangat penting. Beritahu pendapat anda & cadangkan penambahbaikan.',
'feedback.questionTitle': 'Bagaimana anda menilai pengalaman dengan AgriPadi?',
'feedback.positive': 'Maklum Balas Positif',
'feedback.positiveDescription': 'Kongsikan apa yang anda suka tentang sistem',
'feedback.improvement': 'Cadangan Penambahbaikan',
'feedback.improvementDescription': 'Beritahu isu yang anda hadapi atau cadangan penambahbaikan',
'feedback.form.positiveTitle': 'Kongsikan Maklum Balas Positif Anda',
'feedback.form.improvementTitle': 'Apa yang boleh kami perbaiki?',
'feedback.form.feature': 'Ciri/Modul (Pilihan)',
'feedback.form.selectFeature': 'Pilih ciri (pilihan)',
'feedback.form.feature.learning': 'Bahan Pembelajaran',
'feedback.form.feature.virtualTour': 'Lawatan Maya Ladang',
'feedback.form.feature.reporting': 'Sistem Pelaporan',
'feedback.form.feature.forum': 'Forum Komuniti',
'feedback.form.feature.announcements': 'Pengumuman',
'feedback.form.feature.overall': 'Keseluruhan Sistem',
'feedback.form.rating': 'Penilaian (Pilihan)',
'feedback.form.ratingScale': '1 = Sangat Tidak Puas, 5 = Sangat Puas',
'feedback.form.messagePositive': 'Beritahu kami apa yang anda suka',
'feedback.form.messageImprovement': 'Beritahu kami apa yang perlu diperbaiki',
'feedback.form.placeholderPositive': 'Contoh: Bahan pembelajaran sangat membantu & mudah difahami...',
'feedback.form.placeholderImprovement': 'Contoh: Sistem pelaporan agak mengelirukan. Akan lebih baik jika...',
'feedback.form.submit': 'Hantar Maklum Balas',
'feedback.form.submitting': 'Sedang dihantar...',
'feedback.form.cancel': 'Batal',
'feedback.howHelps.title': 'Bagaimana Maklum Balas Anda Membantu',
'feedback.howHelps.improveFeatures': 'Perbaiki Ciri',
'feedback.howHelps.improveFeaturesDesc': 'Maklum balas anda bantu kami kenal pasti ciri yang baik & yang perlu diperbaiki.',
'feedback.howHelps.addFeatures': 'Tambah Ciri Baharu',
'feedback.howHelps.addFeaturesDesc': 'Cadangan anda dipertimbangkan untuk pembangunan ciri baharu AgriPadi.',
'feedback.howHelps.betterExperience': 'Pengalaman Lebih Baik',
'feedback.howHelps.betterExperienceDesc': 'Input anda terus menyumbang menjadikan AgriPadi lebih mesra pengguna.',


       // Virtual Tour Page
'virtualTour.title': 'Lawatan Maya 360°',
'virtualTour.subtitle': 'Terokai sawah padi melalui lawatan interaktif',
'virtualTour.noTours': 'Belum ada lawatan maya buat masa ini',
'virtualTour.viewTour': 'Lihat Lawatan',
'virtualTour.openTour': 'Buka Lawatan',
'virtualTour.instructions': 'Panduan:',
'virtualTour.instructionMouse': 'Gunakan tetikus untuk lihat sekeliling',
'virtualTour.instructionDrag': 'Klik & seret untuk berputar',
'virtualTour.instructionFullscreen': 'Klik butang fullscreen untuk paparan penuh',
'virtualTour.close': 'Tutup',
'virtualTour.360Tour': 'Lawatan Sawah Padi 360°',

// Admin Announcements Page
'adminAnnouncements.title': 'Urus Pengumuman',
'adminAnnouncements.subtitle': 'Cipta & urus pengumuman untuk petani',
'adminAnnouncements.createNew': 'Buat Pengumuman',
'adminAnnouncements.stats.total': 'Jumlah Pengumuman',
'adminAnnouncements.stats.published': 'Telah Diterbitkan',
'adminAnnouncements.stats.draft': 'Draf',
'adminAnnouncements.noAnnouncements': 'Belum ada pengumuman dijumpai',
'adminAnnouncements.published': 'Diterbitkan',
'adminAnnouncements.draft': 'Draf',
'adminAnnouncements.view': 'Lihat',
'adminAnnouncements.unpublish': 'Nyahterbit',
'adminAnnouncements.publish': 'Terbitkan',
'adminAnnouncements.edit': 'Edit',
'adminAnnouncements.delete': 'Padam',
'adminAnnouncements.deleteConfirm': 'Padam pengumuman ini? Tindakan tidak boleh dibatalkan',
'adminAnnouncements.by': 'Oleh',
'adminAnnouncements.form.createTitle': 'Buat Pengumuman Baharu',
'adminAnnouncements.form.createDescription': 'Cipta pengumuman untuk dipaparkan kepada petani',
'adminAnnouncements.form.editTitle': 'Edit Pengumuman',
'adminAnnouncements.form.editDescription': 'Kemaskini butiran pengumuman',
'adminAnnouncements.form.title': 'Tajuk *',
'adminAnnouncements.form.titlePlaceholder': 'Contoh: Bengkel Kawalan Perosak',
'adminAnnouncements.form.category': 'Kategori (Pilihan)',
'adminAnnouncements.form.selectCategory': 'Pilih kategori (pilihan)',
'adminAnnouncements.form.category.workshop': 'Bengkel',
'adminAnnouncements.form.category.program': 'Program',
'adminAnnouncements.form.category.news': 'Berita',
'adminAnnouncements.form.category.warning': 'Amaran',
'adminAnnouncements.form.category.other': 'Lain-lain',
'adminAnnouncements.form.content': 'Kandungan *',
'adminAnnouncements.form.contentPlaceholder': 'Masukkan kandungan pengumuman...',
'adminAnnouncements.form.image': 'Poster/Gambar (Pilihan)',
'adminAnnouncements.form.imageFormat': 'Saiz maks 5MB. Format: JPG, PNG, GIF',
'adminAnnouncements.form.currentImage': 'Gambar Semasa',
'adminAnnouncements.form.newImage': 'Gambar Baharu (Pilihan)',
'adminAnnouncements.form.imageMax': 'Saiz maks 5MB',
'adminAnnouncements.form.publishNow': 'Terbitkan Sekarang',
'adminAnnouncements.form.cancel': 'Batal',
'adminAnnouncements.form.creating': 'Sedang dicipta...',
'adminAnnouncements.form.create': 'Buat Pengumuman',
'adminAnnouncements.form.saving': 'Sedang disimpan...',
'adminAnnouncements.form.save': 'Simpan Perubahan',

// Admin Learning Page
'adminLearning.title': 'Urus Bahan Pembelajaran',
'adminLearning.subtitle': 'Muat naik & urus sumber pendidikan untuk petani',
'adminLearning.addMaterial': 'Tambah Bahan',
'adminLearning.stats.total': 'Jumlah Bahan',
'adminLearning.stats.categories': 'Kategori',
'adminLearning.stats.videos': 'Video YouTube',
'adminLearning.stats.pdfs': 'Dokumen PDF',
'adminLearning.all': 'Semua',
'adminLearning.uploadedBy': 'Dimuat naik oleh',
'adminLearning.viewPdf': 'Lihat PDF',
'adminLearning.watchVideo': 'Tonton Video',
'adminLearning.noMaterials': 'Belum ada bahan pembelajaran. Klik "Tambah Bahan" untuk mula.',
'adminLearning.deleteConfirm': 'Padam bahan ini? Tindakan tidak boleh dibatalkan',
'adminLearning.video': 'Video',
'adminLearning.pdf': 'PDF',
'adminLearning.form.title': 'Tambah Bahan Pembelajaran',
'adminLearning.form.description': 'Muat naik video YouTube atau dokumen PDF untuk petani',
'adminLearning.form.titleLabel': 'Tajuk *',
'adminLearning.form.titlePlaceholder': 'Masukkan tajuk bahan pembelajaran',
'adminLearning.form.descriptionLabel': 'Penerangan',
'adminLearning.form.descriptionPlaceholder': 'Terangkan kandungan bahan pembelajaran...',
'adminLearning.form.categoryLabel': 'Kategori *',
'adminLearning.form.selectCategory': 'Pilih kategori',
'adminLearning.form.newCategory': 'Atau masukkan kategori baharu',
'adminLearning.form.categoryExample': 'Contoh: Serangga Perosak, Pengurusan Tanaman, Baja & Racun, dll.',
'adminLearning.form.typeLabel': 'Jenis Bahan *',
'adminLearning.form.videoYoutube': 'Video YouTube',
'adminLearning.form.pdfDocument': 'Dokumen PDF',
'adminLearning.form.videoUrl': 'URL Video YouTube *',
'adminLearning.form.videoUrlPlaceholder': 'https://www.youtube.com/watch?v=...',
'adminLearning.form.pdfFile': 'Fail PDF *',
'adminLearning.form.uploadPdf': 'Klik untuk muat naik PDF (Maksimum: 50MB)',
'adminLearning.form.cancel': 'Batal',
'adminLearning.form.uploading': 'Sedang dimuat naik...',
'adminLearning.form.upload': 'Muat Naik',


        // Admin Forum Page
'adminForum.title': 'Urus Forum',
'adminForum.subtitle': 'Semak & urus forum yang dihantar oleh petani',
'adminForum.stats.total': 'Jumlah Forum',
'adminForum.stats.pending': 'Menunggu Semakan',
'adminForum.stats.approved': 'Diluluskan',
'adminForum.stats.rejected': 'Ditolak',
'adminForum.filter.all': 'Semua',
'adminForum.filter.pending': 'Menunggu',
'adminForum.filter.approved': 'Diluluskan',
'adminForum.filter.rejected': 'Ditolak',
'adminForum.noForums': 'Belum ada forum dijumpai',
'adminForum.status.pending': 'Menunggu',
'adminForum.status.approved': 'Diluluskan',
'adminForum.status.rejected': 'Ditolak',
'adminForum.rejectionReason': 'Sebab Ditolak:',
'adminForum.likes': 'Suka',
'adminForum.comments': 'Komen',
'adminForum.viewFull': 'Lihat Penuh',
'adminForum.approve': 'Luluskan',
'adminForum.reject': 'Tolak',
'adminForum.delete': 'Padam',
'adminForum.approveConfirm': 'Luluskan forum ini?',
'adminForum.deleteConfirm': 'Padam forum ini? Tindakan tidak boleh dibatalkan.',
'adminForum.form.rejectTitle': 'Tolak Forum',
'adminForum.form.rejectDescription': 'Berikan sebab penolakan forum ini (pilihan)',
'adminForum.form.rejectionReasonLabel': 'Sebab Penolakan (Pilihan)',
'adminForum.form.rejectionReasonPlaceholder': 'Contoh: Kandungan tidak sesuai atau melanggar garis panduan komuniti',
'adminForum.form.cancel': 'Batal',
'adminForum.form.rejectButton': 'Tolak Forum',

// Admin Feedback Page
'adminFeedback.title': 'Maklum Balas Petani',
'adminFeedback.subtitle': 'Semak & analisis maklum balas daripada petani',
'adminFeedback.stats.total': 'Jumlah Maklum Balas',
'adminFeedback.stats.positive': 'Positif',
'adminFeedback.stats.improvement': 'Penambahbaikan',
'adminFeedback.stats.unread': 'Belum Dibaca',
'adminFeedback.stats.averageRating': 'Purata Penilaian',
'adminFeedback.tab.all': 'Semua',
'adminFeedback.tab.positive': 'Positif',
'adminFeedback.tab.improvement': 'Penambahbaikan',
'adminFeedback.featureSatisfaction': 'Kepuasan Ciri',
'adminFeedback.noFeedback': 'Belum ada maklum balas dijumpai',
'adminFeedback.from': 'Daripada:',
'adminFeedback.feature': 'Ciri:',
'adminFeedback.unread': 'Belum Dibaca',
'adminFeedback.markAsRead': 'Tandakan Telah Dibaca',
'adminFeedback.delete': 'Padam',
'adminFeedback.deleteConfirm': 'Padam maklum balas ini? Tindakan tidak boleh dibatalkan.',
'adminFeedback.positive': 'Maklum Balas Positif',
'adminFeedback.improvement': 'Cadangan Penambahbaikan',
'adminFeedback.type.positive': 'Maklum Balas Positif',
'adminFeedback.type.improvement': 'Cadangan Penambahbaikan',
'adminFeedback.new': 'Baru',
'adminFeedback.satisfactionRate': 'Kadar Kepuasan',
'adminFeedback.basedOn': 'Berdasarkan',
'adminFeedback.feedbackCount': 'maklum balas',
'adminFeedback.filter.all': 'Semua',
'adminFeedback.filter.positive': 'Positif',
'adminFeedback.filter.improvement': 'Penambahbaikan',
'adminFeedback.recentFeedback': 'Maklum Balas Terkini',
'adminFeedback.summary': 'Ringkasan',
'adminFeedback.readStatus': 'Status Bacaan',

// Admin Virtual Tour Page
'adminVirtualTour.title': 'Urus Lawatan Maya',
'adminVirtualTour.subtitle': 'Urus lawatan maya 360° untuk petani',
'adminVirtualTour.createNew': 'Buat Lawatan Maya',
'adminVirtualTour.stats.total': 'Jumlah Lawatan',
'adminVirtualTour.stats.published': 'Telah Diterbitkan',
'adminVirtualTour.stats.draft': 'Draf',
'adminVirtualTour.noTours': 'Belum ada lawatan maya dijumpai',
'adminVirtualTour.published': 'Diterbitkan',
'adminVirtualTour.draft': 'Draf',
'adminVirtualTour.view': 'Lihat',
'adminVirtualTour.unpublish': 'Nyahterbit',
'adminVirtualTour.publish': 'Terbitkan',
'adminVirtualTour.edit': 'Edit',
'adminVirtualTour.delete': 'Padam',
'adminVirtualTour.deleteConfirm': 'Padam lawatan maya ini? Tindakan tidak boleh dibatalkan.',
'adminVirtualTour.by': 'Oleh:',
'adminVirtualTour.form.createTitle': 'Buat Lawatan Maya Baharu',
'adminVirtualTour.form.editTitle': 'Edit Lawatan Maya',
'adminVirtualTour.form.title': 'Tajuk *',
'adminVirtualTour.form.titlePlaceholder': 'Masukkan tajuk lawatan maya',
'adminVirtualTour.form.description': 'Penerangan *',
'adminVirtualTour.form.descriptionPlaceholder': 'Terangkan lawatan maya ini...',
'adminVirtualTour.form.tourUrl': 'URL Lawatan *',
'adminVirtualTour.form.tourUrlPlaceholder': 'Masukkan URL lawatan maya 360°',
'adminVirtualTour.form.tourType': 'Jenis Lawatan *',
'adminVirtualTour.form.iframe': 'Terbenam (Iframe)',
'adminVirtualTour.form.redirect': 'Pautan Luar (Redirect)',
'adminVirtualTour.form.thumbnail': 'Thumbnail (Pilihan)',
'adminVirtualTour.form.thumbnailCurrent': 'Thumbnail Semasa',
'adminVirtualTour.form.thumbnailNew': 'Thumbnail Baharu (Pilihan)',
'adminVirtualTour.form.publishNow': 'Terbitkan Sekarang',
'adminVirtualTour.form.cancel': 'Batal',
'adminVirtualTour.form.creating': 'Sedang dicipta...',
'adminVirtualTour.form.create': 'Buat Lawatan',
'adminVirtualTour.form.saving': 'Sedang disimpan...',
'adminVirtualTour.form.save': 'Simpan Perubahan',
'adminVirtualTour.form.displayType': 'Jenis Paparan *',
'adminVirtualTour.form.displayTypeHint': 'Pilih cara lawatan dipaparkan',
'adminVirtualTour.form.url': 'URL *',
'adminVirtualTour.form.urlHint': 'Masukkan pautan penuh bermula dengan https://',
'adminVirtualTour.save': 'Simpan',
'adminVirtualTour.cancel': 'Batal',



        // Admin Users Page
        'adminUsers.title': 'Pengurusan Pengguna',
        'adminUsers.subtitle': 'Urus akaun pengguna dan kebenaran',
        'adminUsers.createNew': 'Tambah Pengguna',
        'adminUsers.usersList': 'Senarai Pengguna',
        'adminUsers.searchPlaceholder': 'Cari pengguna...',
        'adminUsers.table.user': 'Pengguna',
        'adminUsers.table.email': 'E-mel',
        'adminUsers.table.location': 'Lokasi',
        'adminUsers.table.role': 'Peranan',
        'adminUsers.table.registeredDate': 'Tarikh Daftar',
        'adminUsers.table.actions': 'Tindakan',
        'adminUsers.stats.total': 'Jumlah Pengguna',
        'adminUsers.stats.admins': 'Admin',
        'adminUsers.stats.farmers': 'Petani',
        'adminUsers.stats.active': 'Aktif',
        'adminUsers.filter.all': 'Semua Peranan',
        'adminUsers.filter.admin': 'Admin',
        'adminUsers.filter.farmer': 'Petani',
        'adminUsers.search': 'Cari pengguna...',
        'adminUsers.noUsers': 'Tiada pengguna dijumpai',
        'adminUsers.role.admin': 'Admin',
        'adminUsers.role.farmer': 'Petani',
        'adminUsers.active': 'Aktif',
        'adminUsers.inactive': 'Tidak Aktif',
        'adminUsers.edit': 'Edit',
        'adminUsers.delete': 'Padam',
        'adminUsers.deleteConfirm': 'Adakah anda pasti mahu memadam pengguna ini?',
        'adminUsers.form.createTitle': 'Tambah Pengguna Baru',
        'adminUsers.form.createSubtitle': 'Masukkan butiran untuk pengguna baharu',
        'adminUsers.form.editTitle': 'Edit Pengguna',
        'adminUsers.form.editSubtitle': 'Kemaskini butiran pengguna',
        'adminUsers.form.name': 'Nama *',
        'adminUsers.form.namePlaceholder': 'Masukkan nama penuh',
        'adminUsers.form.email': 'E-mel *',
        'adminUsers.form.emailPlaceholder': 'Masukkan alamat e-mel',
        'adminUsers.form.phone': 'No. Telefon',
        'adminUsers.form.phonePlaceholder': 'Masukkan no. telefon',
        'adminUsers.form.address': 'Alamat',
        'adminUsers.form.addressPlaceholder': 'Masukkan alamat',
        'adminUsers.form.role': 'Peranan *',
        'adminUsers.form.selectRole': 'Pilih peranan',
        'adminUsers.form.location': 'Lokasi',
        'adminUsers.form.locationPlaceholder': 'Masukkan lokasi',
        'adminUsers.form.password': 'Kata Laluan *',
        'adminUsers.form.passwordPlaceholder': 'Minimum 8 aksara',
        'adminUsers.form.passwordEdit': 'Kata Laluan Baru (pilihan)',
        'adminUsers.form.passwordEditPlaceholder': 'Biarkan kosong untuk kekalkan kata laluan semasa',
        'adminUsers.form.passwordHint': 'Biarkan kosong untuk kekalkan kata laluan semasa',
        'adminUsers.cancel': 'Batal',
        'adminUsers.adding': 'Menambah...',
        'adminUsers.addUser': 'Tambah Pengguna',
        'adminUsers.updating': 'Mengemaskini...',
        'adminUsers.update': 'Kemaskini',
        'adminUsers.form.cancel': 'Batal',
        'adminUsers.form.creating': 'Mencipta...',
        'adminUsers.form.create': 'Cipta Pengguna',
        'adminUsers.form.saving': 'Menyimpan...',
        'adminUsers.form.save': 'Simpan Perubahan',

        // Admin Reports Page
        'adminReports.title': 'Pengurusan Laporan Petani',
        'adminReports.subtitle': 'Urus dan balas laporan daripada petani',
        'adminReports.tab.all': 'Semua Laporan',
        'adminReports.tab.pending': 'Menunggu',
        'adminReports.tab.resolved': 'Selesai',
        'adminReports.cardTitle.all': 'Semua Laporan',
        'adminReports.cardTitle.pending': 'Laporan Menunggu',
        'adminReports.cardTitle.resolved': 'Laporan Selesai',
        'adminReports.table.report': 'Laporan',
        'adminReports.table.farmer': 'Petani',
        'adminReports.table.type': 'Jenis',
        'adminReports.table.date': 'Tarikh',
        'adminReports.table.status': 'Status',
        'adminReports.table.actions': 'Tindakan',
        'adminReports.noReports': 'Tiada laporan dijumpai',
        'adminReports.status.pending': 'Menunggu',
        'adminReports.status.underReview': 'Dalam Semakan',
        'adminReports.status.resolved': 'Selesai',
        'adminReports.viewDetails': 'Lihat Butiran',

        // Admin Quiz Edit Page
        'adminQuizEdit.title': 'Edit Kuiz',
        'adminQuizEdit.subtitle': 'Kemaskini butiran kuiz dan soalan',
        'adminQuizEdit.breadcrumb': 'Edit Kuiz',
        'adminQuizEdit.saving': 'Menyimpan...',
        'adminQuizEdit.saveChanges': 'Simpan Perubahan',

        // Settings Layout
        'settings.title': 'Tetapan',
        'settings.description': 'Urus profil dan tetapan akaun anda',
        'settings.backToDashboard': 'Kembali ke Papan Pemuka',
        'settings.tabs.profile': 'Profil',
        'settings.tabs.password': 'Kata Laluan',

        // Settings Profile Page
        'settings.profile.title': 'Maklumat Profil',
        'settings.profile.description': 'Kemaskini gambar profil, nama, lokasi dan alamat e-mel anda',
        'settings.profile.language': 'Bahasa',
        'settings.profile.languageDescription': 'Pilih bahasa pilihan anda untuk sistem',
        'settings.profile.profilePicture': 'Gambar Profil',
        'settings.profile.profilePictureNote': 'JPG, PNG atau GIF (MAKS. 2MB)',
        'settings.profile.name': 'Nama',
        'settings.profile.namePlaceholder': 'Nama penuh',
        'settings.profile.email': 'Alamat E-mel',
        'settings.profile.emailPlaceholder': 'Alamat e-mel',
        'settings.profile.location': 'Lokasi',
        'settings.profile.locationPlaceholder': 'cth., Kuala Lumpur, Selangor',
        'settings.profile.emailUnverified': 'Alamat e-mel anda belum disahkan.',
        'settings.profile.resendVerification': 'Klik di sini untuk menghantar semula e-mel pengesahan.',
        'settings.profile.verificationSent': 'Pautan pengesahan baharu telah dihantar ke alamat e-mel anda.',
        'settings.profile.save': 'Simpan',
        'settings.profile.saved': 'Disimpan',

        // Settings Password Page
        'settings.password.title': 'Kemaskini Kata Laluan',
        'settings.password.description': 'Pastikan akaun anda menggunakan kata laluan yang panjang dan rawak untuk kekal selamat',
        'settings.password.currentPassword': 'Kata Laluan Semasa',
        'settings.password.currentPasswordPlaceholder': 'Kata laluan semasa',
        'settings.password.newPassword': 'Kata Laluan Baharu',
        'settings.password.newPasswordPlaceholder': 'Kata laluan baharu',
        'settings.password.confirmPassword': 'Sahkan Kata Laluan',
        'settings.password.confirmPasswordPlaceholder': 'Sahkan kata laluan',
        'settings.password.save': 'Simpan Kata Laluan',
        'settings.password.saved': 'Disimpan',
    },
    en: {
        // Common
        'language': 'Language',
        'dashboard': 'Dashboard',
        'settings': 'Settings',
        'logout': 'Logout',
        'profile': 'Profile',
        'notifications': 'Notifications',
        'menu': 'Menu',
        'closeMenu': 'Close menu',

        // App Header
        'header.tagline': 'Empowering Farmers Through Technology 🌾',

        // Farmer Dashboard
        'farmer.dashboard.title': 'Farmer Home',
        'farmer.dashboard.subtitle': 'Make farm work more organized and easier',
        'farmer.dashboard.welcome': 'Hi {name}! Great to see you again 👋',
        'farmer.dashboard.description': 'A comprehensive and easy-to-use rice farming learning system',
        'farmer.dashboard.startLearning': 'Start Learning',
        'farmer.dashboard.statistics': 'Statistics Summary',
        'farmer.dashboard.quickAccess': 'Quick Access Modules',
        'farmer.dashboard.recentUpdates': 'Recent Updates',
        'farmer.dashboard.viewAll': 'View all',
        'farmer.dashboard.noUpdates': 'No recent updates',
        'farmer.dashboard.checkLater': 'Check back later for new updates',
        'farmer.dashboard.pendingReports': 'pending reports',
        'farmer.dashboard.pendingReportsNeedAction': 'require your attention',
        'farmer.dashboard.unreadAnnouncements': 'new announcements',
        'farmer.dashboard.fromAdmin': 'from administrator',

        // Admin Dashboard
        'admin.dashboard.title': 'Admin Dashboard',
        'admin.dashboard.subtitle': 'System monitoring and administrative action management',
        'admin.dashboard.urgentAction': 'Reports Requiring Immediate Action',
        'admin.dashboard.urgentDescription': 'There are pending reports that need to be reviewed and responded to',
        'admin.dashboard.reviewNow': 'Review Now',
        'admin.dashboard.priorityActions': 'Priority Actions',
        'admin.dashboard.contentManagement': 'Content Management',
        'admin.dashboard.quickActions': 'Quick Actions',
        'admin.dashboard.reportsRequiringAction': 'Reports Requiring Action',
        'admin.dashboard.recentRegistrations': 'Recent Registrations',
        'admin.dashboard.pendingReports': 'Pending Reports',
        'admin.dashboard.inReview': 'In Review',
        'admin.dashboard.resolved': 'Resolved',
        'admin.dashboard.totalUsers': 'Total Users',
        'admin.dashboard.actionRequired': 'Action Required',
        'admin.dashboard.allHandled': 'All reports have been handled',
        'admin.dashboard.continueReview': 'Continue Review',
        'admin.dashboard.noInProcess': 'No reports in process',
        'admin.dashboard.resolvedThisMonth': 'Reports resolved this month',
        'admin.dashboard.farmersAndAdmins': 'Farmers • Admins',
        'admin.dashboard.manageForum': 'Manage Forum',
        'admin.dashboard.addContent': 'Add Content',
        'admin.dashboard.createAnnouncement': 'Create Announcement',
        'admin.dashboard.noPendingReports': 'No Pending Reports',
        'admin.dashboard.allProcessed': 'All reports have been processed successfully',
        'admin.dashboard.noNewRegistrations': 'No New Registrations',
        'admin.dashboard.checkBackForNew': 'Check back for new users',
        'admin.dashboard.highPriority': 'HIGH',
        'admin.dashboard.mediumPriority': 'MEDIUM',
        'admin.dashboard.reviewReports': 'Review Reports',
        'admin.dashboard.mainAction': 'Main action',
        'admin.dashboard.notifyFarmers': 'Notify farmers',
        'admin.dashboard.farmersAdmins': 'Farmers & admins',
        'admin.dashboard.learningMaterials': 'Learning materials',
        'admin.dashboard.menuAdmin': 'Admin Menu',

        // Modules
        'modules.learning': 'Continue Learning',
        'modules.learning.desc': 'Learn about rice farming in a simple and clear way',
        'modules.virtualTour': 'Virtual Farm Tour',
        'modules.virtualTour.desc': 'Explore model farms through 360° virtual tour technology',
        'modules.announcements': 'Announcements',
        'modules.announcements.desc': 'View latest news and important information from administrators',
        'modules.reports': 'Reporting',
        'modules.reports.desc': 'Submit farm problem reports with images and location',
        'modules.forum': 'Community Forum',
        'modules.forum.desc': 'Discuss, ask questions and share experiences with other farmers',
        'modules.feedback': 'Feedback',
        'modules.feedback.desc': 'Share your suggestions to improve the AgriPadi system',

        // Stats
        'stats.materialsAvailable': 'Materials Available',
        'stats.communityMembers': 'Community Members',
        'stats.forumTopics': 'Forum Topics',
        'stats.videosDocuments': 'Videos & Guide Documents',
        'stats.activeFarmers': 'Active Registered Farmers',
        'stats.discussions': 'Discussions & Questions',
        'stats.pendingReports': 'Pending Reports',
        'stats.inReview': 'In Review',
        'stats.resolved': 'Resolved',
        'stats.totalUsers': 'Total Users',

        // Actions
        'actions.accessNow': 'Access now',
        'actions.viewAll': 'View all',
        'actions.viewAllAlt': 'View All',
        'actions.reviewReports': 'Review Reports',
        'actions.createAnnouncement': 'Create Announcement',
        'actions.manageUsers': 'Manage Users',
        'actions.uploadContent': 'Upload Content',

        // Time
        'time.monthsAgo': 'months ago',
        'time.daysAgo': 'days ago',
        'time.hoursAgo': 'hours ago',
        'time.minutesAgo': 'minutes ago',

        // Navigation
        'nav.dashboard': 'Dashboard',
        'nav.userManagement': 'User Management',
        'nav.learning': 'Learning Materials',
        'nav.virtualTour': 'Virtual Farm Tour',
        'nav.announcements': 'Announcements',
        'nav.reports': 'Reporting',
        'nav.forum': 'Community Forum',
        'nav.feedback': 'Feedback',
        'nav.settings': 'Account Settings',
        'nav.priorityActions': 'Priority Actions',
        'nav.management': 'Management',
        'nav.contentManagement': 'Content Management',
        'nav.learningSection': 'Learning',
        'nav.communicationSection': 'Communication',

        // Roles
        'role.farmer': 'Farmer',
        'role.admin': 'System Administrator',
        'role.farmerShort': 'Farmer',
        'role.adminShort': 'Admin',

        // Announcements Page
        'announcements.title': 'Announcements',
        'announcements.subtitle': 'Stay updated with the latest news and announcements',
        'announcements.noAnnouncements': 'No announcements at this time',
        'announcements.by': 'By',

        // Learning Materials Page
        'learning.title': 'Learning Materials',
        'learning.subtitle': 'Access agricultural videos and learning documents',
        'learning.totalMaterials': 'Total Materials',
        'learning.youtubeVideos': 'YouTube Videos',
        'learning.pdfDocuments': 'PDF Documents',
        'learning.searchPlaceholder': 'Search learning materials...',
        'learning.category': 'Category',
        'learning.allCategories': 'All',
        'learning.video': 'Video',
        'learning.pdf': 'PDF',
        'learning.videoYoutube': 'YouTube Video',
        'learning.pdfDocument': 'PDF Document',
        'learning.noMaterialsFound': 'No learning materials found',
        'learning.noMaterialsAvailable': 'No learning materials available',
        'learning.pdfAvailable': 'PDF document available for download',
        'learning.openPdf': 'Open PDF',
        'learning.uploadedBy': 'Uploaded by',

        // Reports Page
        'reports.title': 'Farm Reporting',
        'reports.subtitle': 'Report problems or issues on your farm',
        'reports.submitNew': 'Submit New Report',
        'reports.noReports': 'No reports. Click the button above to create a new report.',
        'reports.viewDetails': 'View Details',
        'reports.edit': 'Edit',
        'reports.delete': 'Delete',
        'reports.confirmDelete': 'Are you sure you want to delete this report?',
        'reports.status.pending': 'Pending',
        'reports.status.under_review': 'Under Review',
        'reports.status.resolved': 'Resolved',
        'reports.adminResponse': 'Response from Agricultural Officer',
        'reports.respondedOn': 'Responded on',
        'reports.submittedOn': 'Submitted on',
        'reports.type': 'Type',
        'reports.location': 'Location',
        'reports.description': 'Description',
        'reports.image': 'Image',
        'reports.pdfLetter': 'PDF Letter',
        'reports.viewPdfLetter': 'View PDF Letter',
        'reports.close': 'Close',

        // Report Form
        'reports.form.createTitle': 'Submit New Report',
        'reports.form.createDescription': 'Fill in information about the problem on your farm',
        'reports.form.editTitle': 'Edit Report',
        'reports.form.editDescription': 'Update your report information',
        'reports.form.reportTitle': 'Report Title *',
        'reports.form.titlePlaceholder': 'Example: Water Supply Issue',
        'reports.form.problemType': 'Problem Type *',
        'reports.form.selectProblemType': 'Select problem type',
        'reports.form.type.irrigation': 'Irrigation Issues',
        'reports.form.type.pestControl': 'Pest Control',
        'reports.form.type.soilManagement': 'Soil Management',
        'reports.form.type.plantDisease': 'Plant Disease',
        'reports.form.type.other': 'Other',
        'reports.form.farmLocation': 'Farm Location *',
        'reports.form.locationPlaceholder': 'Example: Lot 123, Kampung Sungai Petani, Kedah',
        'reports.form.problemDescription': 'Problem Description *',
        'reports.form.descriptionPlaceholder': 'Describe the problem you are facing...',
        'reports.form.imageOptional': 'Image (Optional)',
        'reports.form.clickToUploadImage': 'Click to upload image',
        'reports.form.imageFormat': 'PNG, JPG, GIF up to 10MB',
        'reports.form.pdfLetterOptional': 'PDF Letter (Optional)',
        'reports.form.clickToUploadPdf': 'Click to upload PDF letter',
        'reports.form.pdfFormat': 'PDF up to 10MB',
        'reports.form.cancel': 'Cancel',
        'reports.form.submit': 'Submit Report',
        'reports.form.submitting': 'Submitting...',
        'reports.form.update': 'Update',
        'reports.form.updating': 'Updating...',
        'reports.form.newImage': 'New Image (Optional)',
        'reports.form.newPdf': 'New PDF Letter (Optional)',
        'reports.form.leaveBlankNoChange': 'Leave blank if you don\'t want to change',
        'reports.form.detailsTitle': 'Report Details',

        // Forum Page
        'forum.title': 'Community Forum',
        'forum.subtitle': 'Share experiences and discuss with other farmers',
        'forum.createNew': 'Create New Forum',
        'forum.noForums': 'No forums found. Create your first forum!',
        'forum.comments': 'Comments',
        'forum.justNow': 'Just now',
        'forum.minutesAgo': 'minutes ago',
        'forum.hoursAgo': 'hours ago',
        'forum.daysAgo': 'days ago',
        'forum.form.createTitle': 'Create New Forum',
        'forum.form.createDescription': 'Your forum will be reviewed by admin before publication',
        'forum.form.title': 'Forum Title *',
        'forum.form.titlePlaceholder': 'Example: How to overcome rice pest problems',
        'forum.form.category': 'Category (Optional)',
        'forum.form.selectCategory': 'Select category (optional)',
        'forum.form.category.pestControl': 'Pest Control',
        'forum.form.category.irrigation': 'Irrigation',
        'forum.form.category.fertilizer': 'Fertilizer',
        'forum.form.category.harvesting': 'Harvesting',
        'forum.form.category.marketing': 'Marketing',
        'forum.form.category.other': 'Other',
        'forum.form.content': 'Content *',
        'forum.form.contentPlaceholder': 'Share your experience, questions or information here...',
        'forum.form.image': 'Image (Optional)',
        'forum.form.imageFormat': 'Maximum 5MB. Format: JPG, PNG, GIF',
        'forum.form.cancel': 'Cancel',
        'forum.form.submit': 'Submit for Review',
        'forum.form.submitting': 'Submitting...',

        // Feedback Page
        'feedback.title': 'Feedback',
        'feedback.subtitle': 'Your feedback is important to us. Tell us your thoughts about this system, and suggest any improvements.',
        'feedback.questionTitle': 'How would you rate your experience with AgriPadi?',
        'feedback.positive': 'Positive Feedback',
        'feedback.positiveDescription': 'Share what you like about the system',
        'feedback.improvement': 'Suggestions for Improvement',
        'feedback.improvementDescription': 'Tell us about issues you faced or suggestions for improvement',
        'feedback.form.positiveTitle': 'Share Your Positive Feedback',
        'feedback.form.improvementTitle': 'What can we improve?',
        'feedback.form.feature': 'Feature/Module (Optional)',
        'feedback.form.selectFeature': 'Select feature (optional)',
        'feedback.form.feature.learning': 'Learning Materials',
        'feedback.form.feature.virtualTour': 'Farm Virtual Tour',
        'feedback.form.feature.reporting': 'Reporting System',
        'feedback.form.feature.forum': 'Community Forum',
        'feedback.form.feature.announcements': 'Announcements',
        'feedback.form.feature.overall': 'Overall System',
        'feedback.form.rating': 'Rating (Optional)',
        'feedback.form.ratingScale': '1 = Very Dissatisfied, 5 = Very Satisfied',
        'feedback.form.messagePositive': 'Tell us what you like',
        'feedback.form.messageImprovement': 'Tell us what needs improvement',
        'feedback.form.placeholderPositive': 'Example: The learning materials are very helpful and easy to understand...',
        'feedback.form.placeholderImprovement': 'Example: The reporting system is a bit confusing to use. It would be better if...',
        'feedback.form.submit': 'Submit Feedback',
        'feedback.form.submitting': 'Submitting...',
        'feedback.form.cancel': 'Cancel',
        'feedback.howHelps.title': 'How Your Feedback Helps',
        'feedback.howHelps.improveFeatures': 'Improve Features',
        'feedback.howHelps.improveFeaturesDesc': 'Your feedback helps us identify features that work well and those that need improvement.',
        'feedback.howHelps.addFeatures': 'Add New Features',
        'feedback.howHelps.addFeaturesDesc': 'We consider your suggestions when developing new features for AgriPadi.',
        'feedback.howHelps.betterExperience': 'Better Experience',
        'feedback.howHelps.betterExperienceDesc': 'Your input directly contributes to making AgriPadi more user-friendly.',

        // Virtual Tour Page
        'virtualTour.title': 'Virtual Tour 360°',
        'virtualTour.subtitle': 'Explore rice fields through interactive virtual tours',
        'virtualTour.noTours': 'No virtual tours available at this time',
        'virtualTour.viewTour': 'View Tour',
        'virtualTour.openTour': 'Open Tour',
        'virtualTour.instructions': 'Instructions:',
        'virtualTour.instructionMouse': 'Use mouse to look around',
        'virtualTour.instructionDrag': 'Click and drag to rotate',
        'virtualTour.instructionFullscreen': 'Use fullscreen button for full display',
        'virtualTour.close': 'Close',
        'virtualTour.360Tour': '360° Tour',

        // Admin Announcements Page
        'adminAnnouncements.title': 'Announcements Management',
        'adminAnnouncements.subtitle': 'Create and manage announcements for farmers',
        'adminAnnouncements.createNew': 'Create Announcement',
        'adminAnnouncements.stats.total': 'Total Announcements',
        'adminAnnouncements.stats.published': 'Published',
        'adminAnnouncements.stats.draft': 'Draft',
        'adminAnnouncements.noAnnouncements': 'No announcements found',
        'adminAnnouncements.published': 'Published',
        'adminAnnouncements.draft': 'Draft',
        'adminAnnouncements.view': 'View',
        'adminAnnouncements.unpublish': 'Unpublish',
        'adminAnnouncements.publish': 'Publish',
        'adminAnnouncements.edit': 'Edit',
        'adminAnnouncements.delete': 'Delete',
        'adminAnnouncements.deleteConfirm': 'Are you sure you want to delete this announcement?',
        'adminAnnouncements.by': 'By:',
        'adminAnnouncements.form.createTitle': 'Create New Announcement',
        'adminAnnouncements.form.createDescription': 'Create an announcement to be displayed to farmers',
        'adminAnnouncements.form.editTitle': 'Edit Announcement',
        'adminAnnouncements.form.editDescription': 'Update announcement details',
        'adminAnnouncements.form.title': 'Title *',
        'adminAnnouncements.form.titlePlaceholder': 'Example: Pest Control Workshop',
        'adminAnnouncements.form.category': 'Category (Optional)',
        'adminAnnouncements.form.selectCategory': 'Select category (optional)',
        'adminAnnouncements.form.category.workshop': 'Workshop',
        'adminAnnouncements.form.category.program': 'Program',
        'adminAnnouncements.form.category.news': 'News',
        'adminAnnouncements.form.category.warning': 'Warning',
        'adminAnnouncements.form.category.other': 'Other',
        'adminAnnouncements.form.content': 'Content *',
        'adminAnnouncements.form.contentPlaceholder': 'Enter announcement content...',
        'adminAnnouncements.form.image': 'Poster/Image (Optional)',
        'adminAnnouncements.form.imageFormat': 'Maximum 5MB. Format: JPG, PNG, GIF',
        'adminAnnouncements.form.currentImage': 'Current Image',
        'adminAnnouncements.form.newImage': 'New Image (Optional)',
        'adminAnnouncements.form.imageMax': 'Maximum 5MB',
        'adminAnnouncements.form.publishNow': 'Publish now',
        'adminAnnouncements.form.cancel': 'Cancel',
        'adminAnnouncements.form.creating': 'Creating...',
        'adminAnnouncements.form.create': 'Create Announcement',
        'adminAnnouncements.form.saving': 'Saving...',
        'adminAnnouncements.form.save': 'Save Changes',

        // Admin Learning Page
        'adminLearning.title': 'Manage Learning Materials',
        'adminLearning.subtitle': 'Upload and manage educational resources for farmers',
        'adminLearning.manageQuiz': 'Manage Quiz',
        'adminLearning.addMaterial': 'Add Material',
        'adminLearning.stats.total': 'Total Materials',
        'adminLearning.stats.categories': 'Categories',
        'adminLearning.stats.videos': 'YouTube Videos',
        'adminLearning.stats.pdfs': 'PDF Documents',
        'adminLearning.all': 'All',
        'adminLearning.uploadedBy': 'Uploaded by',
        'adminLearning.viewPdf': 'View PDF',
        'adminLearning.watchVideo': 'Watch Video',
        'adminLearning.noMaterials': 'No learning materials. Click "Add Material" button to start.',
        'adminLearning.deleteConfirm': 'Are you sure you want to delete this learning material?',
        'adminLearning.video': 'Video',
        'adminLearning.pdf': 'PDF',
        'adminLearning.form.title': 'Add Learning Material',
        'adminLearning.form.description': 'Upload YouTube video or PDF document for farmers',
        'adminLearning.form.titleLabel': 'Title *',
        'adminLearning.form.titlePlaceholder': 'Enter learning material title',
        'adminLearning.form.descriptionLabel': 'Description',
        'adminLearning.form.descriptionPlaceholder': 'Describe the learning material content...',
        'adminLearning.form.categoryLabel': 'Category *',
        'adminLearning.form.selectCategory': 'Select category',
        'adminLearning.form.newCategory': 'Or enter new category',
        'adminLearning.form.categoryExample': 'Example: Pest Insects, Crop Management, Fertilizers & Pesticides, etc.',
        'adminLearning.form.typeLabel': 'Material Type *',
        'adminLearning.form.videoYoutube': 'YouTube Video',
        'adminLearning.form.pdfDocument': 'PDF Document',
        'adminLearning.form.videoUrl': 'YouTube Video URL *',
        'adminLearning.form.videoUrlPlaceholder': 'https://www.youtube.com/watch?v=...',
        'adminLearning.form.pdfFile': 'PDF File *',
        'adminLearning.form.uploadPdf': 'Click to upload PDF (Max: 50MB)',
        'adminLearning.form.cancel': 'Cancel',
        'adminLearning.form.uploading': 'Uploading...',
        'adminLearning.form.upload': 'Upload',

        // Admin Forum Page
        'adminForum.title': 'Forum Management',
        'adminForum.subtitle': 'Manage and review forums submitted by farmers',
        'adminForum.stats.total': 'Total Forums',
        'adminForum.stats.pending': 'Pending',
        'adminForum.stats.approved': 'Approved',
        'adminForum.stats.rejected': 'Rejected',
        'adminForum.filter.all': 'All',
        'adminForum.filter.pending': 'Pending',
        'adminForum.filter.approved': 'Approved',
        'adminForum.filter.rejected': 'Rejected',
        'adminForum.noForums': 'No forums found',
        'adminForum.status.pending': 'Pending',
        'adminForum.status.approved': 'Approved',
        'adminForum.status.rejected': 'Rejected',
        'adminForum.rejectionReason': 'Rejection Reason:',
        'adminForum.likes': 'Likes',
        'adminForum.comments': 'Comments',
        'adminForum.viewFull': 'View Full',
        'adminForum.approve': 'Approve',
        'adminForum.reject': 'Reject',
        'adminForum.delete': 'Delete',
        'adminForum.approveConfirm': 'Are you sure you want to approve this forum?',
        'adminForum.deleteConfirm': 'Are you sure you want to delete this forum? This action cannot be undone.',
        'adminForum.form.rejectTitle': 'Reject Forum',
        'adminForum.form.rejectDescription': 'Please provide a reason for rejecting this forum (optional)',
        'adminForum.form.rejectionReasonLabel': 'Rejection Reason (Optional)',
        'adminForum.form.rejectionReasonPlaceholder': 'Example: Content is inappropriate or violates community guidelines',
        'adminForum.form.cancel': 'Cancel',
        'adminForum.form.rejectButton': 'Reject Forum',

        // Admin Feedback Page
        'adminFeedback.title': 'Farmer Feedback',
        'adminFeedback.subtitle': 'Review and analyze feedback from farmers',
        'adminFeedback.stats.total': 'Total Feedback',
        'adminFeedback.stats.positive': 'Positive',
        'adminFeedback.stats.improvement': 'Improvement',
        'adminFeedback.stats.unread': 'Unread',
        'adminFeedback.stats.averageRating': 'Average Rating',
        'adminFeedback.tab.all': 'All',
        'adminFeedback.tab.positive': 'Positive',
        'adminFeedback.tab.improvement': 'Improvement',
        'adminFeedback.featureSatisfaction': 'Feature Satisfaction',
        'adminFeedback.noFeedback': 'No feedback found',
        'adminFeedback.from': 'From:',
        'adminFeedback.feature': 'Feature:',
        'adminFeedback.unread': 'Unread',
        'adminFeedback.markAsRead': 'Mark as Read',
        'adminFeedback.delete': 'Delete',
        'adminFeedback.deleteConfirm': 'Are you sure you want to delete this feedback?',
        'adminFeedback.positive': 'Positive Feedback',
        'adminFeedback.improvement': 'Improvement Suggestion',
        'adminFeedback.type.positive': 'Positive Feedback',
        'adminFeedback.type.improvement': 'Improvement Suggestion',
        'adminFeedback.new': 'New',
        'adminFeedback.satisfactionRate': 'Satisfaction Rate',
        'adminFeedback.basedOn': 'Based on',
        'adminFeedback.feedbackCount': 'feedback',
        'adminFeedback.filter.all': 'All',
        'adminFeedback.filter.positive': 'Positive',
        'adminFeedback.filter.improvement': 'Improvement',
        'adminFeedback.recentFeedback': 'Recent Feedback',
        'adminFeedback.summary': 'Summary',
        'adminFeedback.readStatus': 'Read Status',

        // Admin Virtual Tour Page
        'adminVirtualTour.title': 'Virtual Tour Management',
        'adminVirtualTour.subtitle': 'Manage 360° virtual tours for farmers',
        'adminVirtualTour.createNew': 'Create Virtual Tour',
        'adminVirtualTour.stats.total': 'Total Tours',
        'adminVirtualTour.stats.published': 'Published',
        'adminVirtualTour.stats.draft': 'Draft',
        'adminVirtualTour.noTours': 'No virtual tours found',
        'adminVirtualTour.published': 'Published',
        'adminVirtualTour.draft': 'Draft',
        'adminVirtualTour.view': 'View',
        'adminVirtualTour.unpublish': 'Unpublish',
        'adminVirtualTour.publish': 'Publish',
        'adminVirtualTour.edit': 'Edit',
        'adminVirtualTour.delete': 'Delete',
        'adminVirtualTour.deleteConfirm': 'Are you sure you want to delete this virtual tour?',
        'adminVirtualTour.by': 'By:',
        'adminVirtualTour.form.createTitle': 'Create New Virtual Tour',
        'adminVirtualTour.form.editTitle': 'Edit Virtual Tour',
        'adminVirtualTour.form.title': 'Title *',
        'adminVirtualTour.form.titlePlaceholder': 'Enter virtual tour title',
        'adminVirtualTour.form.description': 'Description *',
        'adminVirtualTour.form.descriptionPlaceholder': 'Describe this virtual tour...',
        'adminVirtualTour.form.tourUrl': 'Tour URL *',
        'adminVirtualTour.form.tourUrlPlaceholder': 'Enter 360° virtual tour URL',
        'adminVirtualTour.form.tourType': 'Tour Type *',
        'adminVirtualTour.form.iframe': 'Embedded (Iframe)',
        'adminVirtualTour.form.redirect': 'External Link (Redirect)',
        'adminVirtualTour.form.thumbnail': 'Thumbnail (Optional)',
        'adminVirtualTour.form.thumbnailCurrent': 'Current Thumbnail',
        'adminVirtualTour.form.thumbnailNew': 'New Thumbnail (Optional)',
        'adminVirtualTour.form.publishNow': 'Publish now',
        'adminVirtualTour.form.cancel': 'Cancel',
        'adminVirtualTour.form.creating': 'Creating...',
        'adminVirtualTour.form.create': 'Create Tour',
        'adminVirtualTour.form.saving': 'Saving...',
        'adminVirtualTour.form.save': 'Save Changes',
        'adminVirtualTour.form.displayType': 'Display Type *',
        'adminVirtualTour.form.displayTypeHint': 'Choose how the tour is shown',
        'adminVirtualTour.form.url': 'URL *',
        'adminVirtualTour.form.urlHint': 'Enter full link starting with https://',
        'adminVirtualTour.save': 'Save',
        'adminVirtualTour.cancel': 'Cancel',

        // Admin Users Page
        'adminUsers.title': 'User Management',
        'adminUsers.subtitle': 'Manage user accounts and permissions',
        'adminUsers.createNew': 'Add User',
        'adminUsers.usersList': 'Users List',
        'adminUsers.searchPlaceholder': 'Search users...',
        'adminUsers.table.user': 'User',
        'adminUsers.table.email': 'Email',
        'adminUsers.table.location': 'Location',
        'adminUsers.table.role': 'Role',
        'adminUsers.table.registeredDate': 'Registered Date',
        'adminUsers.table.actions': 'Actions',
        'adminUsers.stats.total': 'Total Users',
        'adminUsers.stats.admins': 'Admins',
        'adminUsers.stats.farmers': 'Farmers',
        'adminUsers.stats.active': 'Active',
        'adminUsers.filter.all': 'All Roles',
        'adminUsers.filter.admin': 'Admin',
        'adminUsers.filter.farmer': 'Farmer',
        'adminUsers.search': 'Search users...',
        'adminUsers.noUsers': 'No users found',
        'adminUsers.role.admin': 'Admin',
        'adminUsers.role.farmer': 'Farmer',
        'adminUsers.active': 'Active',
        'adminUsers.inactive': 'Inactive',
        'adminUsers.edit': 'Edit',
        'adminUsers.delete': 'Delete',
        'adminUsers.deleteConfirm': 'Are you sure you want to delete this user?',
        'adminUsers.form.createTitle': 'Add New User',
        'adminUsers.form.createSubtitle': 'Enter details for new user',
        'adminUsers.form.editTitle': 'Edit User',
        'adminUsers.form.editSubtitle': 'Update user details',
        'adminUsers.form.name': 'Name *',
        'adminUsers.form.namePlaceholder': 'Enter full name',
        'adminUsers.form.email': 'Email *',
        'adminUsers.form.emailPlaceholder': 'Enter email address',
        'adminUsers.form.phone': 'Phone Number',
        'adminUsers.form.phonePlaceholder': 'Enter phone number',
        'adminUsers.form.address': 'Address',
        'adminUsers.form.addressPlaceholder': 'Enter address',
        'adminUsers.form.role': 'Role *',
        'adminUsers.form.selectRole': 'Select role',
        'adminUsers.form.location': 'Location',
        'adminUsers.form.locationPlaceholder': 'Enter location',
        'adminUsers.form.password': 'Password *',
        'adminUsers.form.passwordPlaceholder': 'Minimum 8 characters',
        'adminUsers.form.passwordEdit': 'New Password (optional)',
        'adminUsers.form.passwordEditPlaceholder': 'Leave blank to keep current password',
        'adminUsers.form.passwordHint': 'Leave blank to keep current password',
        'adminUsers.cancel': 'Cancel',
        'adminUsers.adding': 'Adding...',
        'adminUsers.addUser': 'Add User',
        'adminUsers.updating': 'Updating...',
        'adminUsers.update': 'Update',
        'adminUsers.form.cancel': 'Cancel',
        'adminUsers.form.creating': 'Creating...',
        'adminUsers.form.create': 'Create User',
        'adminUsers.form.saving': 'Saving...',
        'adminUsers.form.save': 'Save Changes',

        // Admin Reports Page
        'adminReports.title': 'Farmer Report Management',
        'adminReports.subtitle': 'Manage and respond to reports from farmers',
        'adminReports.tab.all': 'All Reports',
        'adminReports.tab.pending': 'Pending',
        'adminReports.tab.resolved': 'Resolved',
        'adminReports.cardTitle.all': 'All Reports',
        'adminReports.cardTitle.pending': 'Pending Reports',
        'adminReports.cardTitle.resolved': 'Resolved Reports',
        'adminReports.table.report': 'Report',
        'adminReports.table.farmer': 'Farmer',
        'adminReports.table.type': 'Type',
        'adminReports.table.date': 'Date',
        'adminReports.table.status': 'Status',
        'adminReports.table.actions': 'Actions',
        'adminReports.noReports': 'No reports found',
        'adminReports.status.pending': 'Pending',
        'adminReports.status.underReview': 'Under Review',
        'adminReports.status.resolved': 'Resolved',
        'adminReports.viewDetails': 'View Details',

        // // Admin Quiz Page
        // 'adminQuiz.title': 'Manage Learning Quizzes',
        // 'adminQuiz.subtitle': 'Create and manage quizzes to test farmer knowledge',
        // 'adminQuiz.addQuiz': 'Add Quiz',
        // 'adminQuiz.stats.totalQuizzes': 'Total Quizzes',
        // 'adminQuiz.stats.activeQuizzes': 'Active Quizzes',
        // 'adminQuiz.stats.inactiveQuizzes': 'Inactive Quizzes',
        // 'adminQuiz.stats.totalAttempts': 'Total Attempts',
        // 'adminQuiz.filterAll': 'All',
        // 'adminQuiz.status.active': 'Active',
        // 'adminQuiz.status.inactive': 'Inactive',
        // 'adminQuiz.questions': 'questions',
        // 'adminQuiz.passingScore': 'Passing score',
        // 'adminQuiz.timeLimit': 'minutes',
        // 'adminQuiz.attempts': 'attempts',
        // 'adminQuiz.relatedTo': 'Related to',
        // 'adminQuiz.createdBy': 'Created by',
        // 'adminQuiz.noQuizzes': 'No quizzes found. Click "Add Quiz" button to start.',
        // 'adminQuiz.deleteConfirm': 'Are you sure you want to delete this quiz? All user attempts will also be deleted.',
        // 'adminQuiz.breadcrumb': 'Learning Quizzes',

        // // Admin Quiz Create Page
        // 'adminQuizCreate.title': 'Create New Quiz',
        // 'adminQuizCreate.subtitle': 'Fill in quiz details and add questions for farmers',
        // 'adminQuizCreate.breadcrumb': 'Add Quiz',
        // 'adminQuizCreate.basicInfo': 'Basic Information',
        // 'adminQuizCreate.quizTitle': 'Quiz Title',
        // 'adminQuizCreate.quizTitlePlaceholder': 'e.g., Pest Management Quiz',
        // 'adminQuizCreate.description': 'Description',
        // 'adminQuizCreate.descriptionPlaceholder': 'Describe this quiz...',
        // 'adminQuizCreate.category': 'Category',
        // 'adminQuizCreate.selectCategory': 'Select category',
        // 'adminQuizCreate.newCategory': 'Or enter new category',
        // 'adminQuizCreate.relatedMaterial': 'Related Learning Material (Optional)',
        // 'adminQuizCreate.selectMaterial': 'Select learning material',
        // 'adminQuizCreate.none': 'None',
        // 'adminQuizCreate.passingScore': 'Passing Score (%)',
        // 'adminQuizCreate.timeLimit': 'Time Limit (Minutes)',
        // 'adminQuizCreate.timeLimitPlaceholder': 'Leave blank for no time limit',
        // 'adminQuizCreate.activateQuiz': 'Activate this quiz (farmers can take the quiz)',
        // 'adminQuizCreate.questionsTitle': 'Questions',
        // 'adminQuizCreate.addQuestion': 'Add Question',
        // 'adminQuizCreate.questionNumber': 'Question',
        // 'adminQuizCreate.questionLabel': 'Question',
        // 'adminQuizCreate.questionPlaceholder': 'Enter question...',
        // 'adminQuizCreate.answerOptions': 'Answer Options',
        // 'adminQuizCreate.optionPlaceholder': 'Option',
        // 'adminQuizCreate.markCorrect': 'Click the ✓ button to mark the correct answer',
        // 'adminQuizCreate.explanation': 'Explanation (Optional)',
        // 'adminQuizCreate.explanationPlaceholder': 'Explain why this answer is correct...',
        // 'adminQuizCreate.explanationNote': 'The explanation will be shown to farmers after they complete the quiz',
        // 'adminQuizCreate.cancel': 'Cancel',
        // 'adminQuizCreate.creating': 'Creating...',
        // 'adminQuizCreate.createQuiz': 'Create Quiz',
        // 'adminQuizCreate.required': '*',

        // // Admin Quiz Edit Page
        // 'adminQuizEdit.title': 'Edit Quiz',
        // 'adminQuizEdit.subtitle': 'Update quiz details and questions',
        // 'adminQuizEdit.breadcrumb': 'Edit Quiz',
        // 'adminQuizEdit.saving': 'Saving...',
        // 'adminQuizEdit.saveChanges': 'Save Changes',

        // Settings Layout
        'settings.title': 'Settings',
        'settings.description': 'Manage your profile and account settings',
        'settings.backToDashboard': 'Back to Dashboard',
        'settings.tabs.profile': 'Profile',
        'settings.tabs.password': 'Password',

        // Settings Profile Page
        'settings.profile.title': 'Profile information',
        'settings.profile.description': 'Update your profile picture, name, location and email address',
        'settings.profile.language': 'Language',
        'settings.profile.languageDescription': 'Select your preferred language for the system',
        'settings.profile.profilePicture': 'Profile Picture',
        'settings.profile.profilePictureNote': 'JPG, PNG or GIF (MAX. 2MB)',
        'settings.profile.name': 'Name',
        'settings.profile.namePlaceholder': 'Full name',
        'settings.profile.email': 'Email address',
        'settings.profile.emailPlaceholder': 'Email address',
        'settings.profile.location': 'Location',
        'settings.profile.locationPlaceholder': 'e.g., Kuala Lumpur, Selangor',
        'settings.profile.emailUnverified': 'Your email address is unverified.',
        'settings.profile.resendVerification': 'Click here to resend the verification email.',
        'settings.profile.verificationSent': 'A new verification link has been sent to your email address.',
        'settings.profile.save': 'Save',
        'settings.profile.saved': 'Saved',

        // Settings Password Page
        'settings.password.title': 'Update password',
        'settings.password.description': 'Ensure your account is using a long, random password to stay secure',
        'settings.password.currentPassword': 'Current password',
        'settings.password.currentPasswordPlaceholder': 'Current password',
        'settings.password.newPassword': 'New password',
        'settings.password.newPasswordPlaceholder': 'New password',
        'settings.password.confirmPassword': 'Confirm password',
        'settings.password.confirmPasswordPlaceholder': 'Confirm password',
        'settings.password.save': 'Save password',
        'settings.password.saved': 'Saved',
    },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguageState] = useState<Language>('ms');

    // Load language preference from localStorage on mount
    useEffect(() => {
        const savedLanguage = localStorage.getItem('agripadi_language') as Language | null;
        if (savedLanguage && (savedLanguage === 'ms' || savedLanguage === 'en')) {
            setLanguageState(savedLanguage);
            document.documentElement.lang = savedLanguage === 'ms' ? 'ms-MY' : 'en-US';
        }
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('agripadi_language', lang);
        document.documentElement.lang = lang === 'ms' ? 'ms-MY' : 'en-US';
    };

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
